apiVersion: admin.enmasse.io/v1beta2
kind: AddressPlan
metadata:
  name: standard-examplepartitioned-queue
  labels:
    app: enmasse
spec:
  displayName: Small Partitioned Queue
  displayOrder: 0
  shortDescription: Creates a small queue that is partitioned across several brokers 
  longDescription: Creates a small queue that is partitioned across several brokers
  addressType: queue
  resources:
    router: 0.001
    broker: 0.01
  partitions: 2
